### ISSUE TITLE
Ugyldig plassering på barnehager

### ISSUE THREAD

**Issue by ghost** [obtitus/barnehagefakta_osm#2]
Barnehagene med ID 1021260 og 1015961 er nesten helt sikkert plassert feil. De står i en tunellmunning på Kolltveit. 
Kan man melde feil plassering et sted og få det fikset?

**Comment by ghost** [comment]
Det virker egentlig som de fleste barnehagene i Fjell kommune er plassert mer eller mindre feil. Jeg hadde tegnet inn nesten alle fra fra før så jeg klarte å koble de sammen, men en node var feks plassert lang inn i nabokommunen. Flere var plassert midt på veier eller i kryss langt unna.

**Comment by ghost** [comment]
Oppdaget nå at jeg kan rapportere feil direkte til NBR her:  https://obtitus.github.io/barnehagefakta_osm_data/1246.html 
Får gjøre det og se om de gjør noe med det

**Comment by obtitus** [comment]
Flott at du fant ut av det. Er ikke så mye annet jeg for gjort enn å kontakte NBR. Er mange kommuner som har helt ville posisjoner, noen putter f.eks. alle barnehagene midt i kommunen...

**Comment by ghost** [comment]
Jeg rapporterte inn en 10 barnehager. Får se om de ornder de eller bare ignorerer det.

On 29 May 2016 15:40:48 CEST, "Øystein Bjørndal" notifications@github.com wrote:

> Flott at du fant ut av det. Er ikke så mye annet jeg for gjort enn å
> kontakte NBR. Er mange kommuner som har helt ville posisjoner, noen
> putter f.eks. alle barnehagene midt i kommunen...
> 
> ---
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/obtitus/barnehagefakta_osm/issues/2#issuecomment-222361184

## 

Fredrik
tlf +47 95853805
