### ISSUE TITLE
Unike navn på kommunefilene (barnehagefakta.osm)

### ISSUE THREAD

**Issue by ghost** [obtitus/barnehagefakta_osm#3]
Nå heter alle filene for alle kommune barnehagefakta.osm og når man laster ned mange blir det fort forvirrende. 
Det hadde vært nyttig hvis filene hadde hett feks barnehagefakta_1245.osm

**Comment by obtitus** [comment]
> On 24 Nov 2017, at 17:17, Fredrik Lindseth <notifications@github.com> wrote:
> 
> Nå heter alle filene for alle kommune barnehagefakta.osm og når man laster ned mange blir det fort forvirrende.
> Det hadde vært nyttig hvis filene hadde hett feks barnehagefakta_1245.osm
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Hei, ser på det nå. Enig at dette kan bli rotete. Filnavnet blir nå 1245_barnehagefakta.osm da det er enklere rent teknisk.
-- 
Øystein Bjørndal

**Comment by obtitus** [comment]
Da er dette fikset. 

Merk at det også ligger en norge_barnehagefakta.osm her: https://raw.githubusercontent.com/POI-Importer/norge-barnehagefakta/master/norge_barnehagefakta.osm som har alle barnehagene i 1 fil om du ønsker det.
