### ISSUE TITLE
Ignorere liten/stor bokstav i sammenligning av felt

### ISSUE THREAD

**Issue by hansfn** [obtitus/barnehagefakta_osm#6]
Svært praktisk når det markeres (med gult) forskjeller i data mellom NBR og OSM, men jeg er usikker på om stor/liten bokstav bør tas med. Eksempel fra [Molde](https://obtitus.github.io/barnehagefakta_osm_data/1502.html):

"operator = Brunstad Kristelige Menighet Molde" VS "operator = Brunstad kristelige Menighet Molde"

Jeg antar jeg har lagt inn data i OSM og prøvd å følge regler for norsk rettskriving ;-)

**Comment by obtitus** [comment]
Tja, her må du nesten ta opp med Brunstad Kristelige Menighet Molde hvorfor de har valgt å ha bare store bokstaver, men det er det bedriften heter, så  da mener jeg at det er det som bør være i OSM. Ser ikke noe bakdel av at html-visningen gjør dette synlig.

For name= taggen behandler vi ting litt anderledes å prøver å fjerne en del feil store/små bokstaver samt navn som f.eks. slutter på AS. Her er det som regel greit om name=* i OSM ikke stemmer helt med name=* i NSR.
Hvis du vil se alle "feilene" vi retter fra NSR før de blir vist på websiden, ligger det her:
https://obtitus.github.io/barnehagefakta_osm_data/data/name_log.csv
med kode i name_cleanup.py

Jeg har uansett ikke lyst at sammenligningen skal være case-insensitive, da det er fint om det blir vist tydelig om noen legger inn
name = "mORDalstuA barnEhage"
i OSM.

PS. Du legger nok også merke til at det er en del gule forskjeller på capacity=*. Her har jeg gitt opp å vedlikeholde OSM hver gang NSR oppdaterer capacity med et par barn +-. ~~Skal se om jeg får ordnet html visningen så den ikke tar det så tungt.~~ Fixed
